### PR TITLE
Fix to bug that was allowing user to enter in a past date

### LINKED ISSUE #85: Bug fix to stop past dates
- [x]  stop the user from submitting a past date

### PR DESCRIPTION
**Pull request by MichaelEWalker87**
# Pull Request Travel-Tracker

#### What’s this PR do?

* This set-up a checker to see if the date is an invalid entry and provides an alert if invalid   

#### Where should the reviewer start?

* Reviewer should start with the index.js

#### How should this be manually tested?

* open the application up in localhost then run a past date and attempt to submit it 

#### Any background context you want to provide?

* This was a known issue and it has now been resolved (however the user is still allowed to select the next day)  

#### What are the relevant tickets?

* bug with calendar 

#### Screenshots (if appropriate):

* none at this time 

#### Questions:

* none at this time

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -237,15 +237,23 @@ let populateAllPages = () => {
...
-    userID: currentTraveler.id,
-    destinationID: parseInt(destinationPicker.value),
-    travelers: parseInt(travelersNumberPicker.value),
-    date: formatedDate,
-    duration: parseInt(travelersDurationPicker.value),
-    status: 'pending',
-    suggestedActivities: []
+  let currentDay = new Date(Date.now())
+  let calenderCheck = new Date(formatedDate)
+  if (calenderCheck > currentDay) {
```
Comment (nathanielmillard) [inline src/index.js:242]: This is a great fix, you can also as a min date value on your html input element so that anything before the date you want is greyed out.

**Review by nathanielmillard — APPROVED** [review]
Glad to see this is working for you, I think it's also worth looking at the UI as well since sometimes not givng them an option in the first place can be a line of defense.
